# Generated by Django 5.1.4 on 2024-12-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='working',
            field=models.BooleanField(default=True),
        ),
    ]
